### ISSUE TITLE
Managed log source for AWS LB logs

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#48]
Add support for managing AWS load balancer logs.

## Tasks

- [x] Classic Load Balancer logs
- [x] Application Load Balancer logs
- [x] Network Load Balancer logs

## References

- Classic ELB logs: https://docs.amazonaws.cn/en_us/elasticloadbalancing/latest/classic/access-log-collection.html
- ALB logs: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html
- NLB logs: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-access-logs.html

**Comment by timoguin** [comment]
@Samrose-Ahmed Do you know if the schemas and transforms you added support all 3 load balancer types, or is it just Application Load Balancers?

**Comment by Samrose-Ahmed** [comment]
They support all three, should make that clearer in the docs.
