### ISSUE TITLE
feat: Managed log source for AWS Config

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#51]
Add support for managing logs (data?) and events from AWS Config. This includes configuration snapshots, configuration history, and configuration streams.

## Considerations

AWS Config sends notifications to SNS for a number of events, the most useful of which is the `ConfigurationItemChangeNotification` and the `ComplianceChangeNotification`. These would be highly useful to ingest.

AWS Config also delivers configuration snapshots and configuration history data to S3.

Another useful event is the `OversizedConfigurationItemChangeNotification`, which delivers configuration change data to S3 in the event that it is too large for an SNS message (so they require additional processing).

## Tasks

- [ ] Configuration Stream support (SNS)
- [ ] Configuration Snapshot support
- [ ] Configuration History support

## References

- Config concepts: https://docs.aws.amazon.com/config/latest/developerguide/config-concepts.html
- Components of a Configuration Item: https://docs.aws.amazon.com/config/latest/developerguide/config-item-table.html
- Example Config notifications: https://docs.aws.amazon.com/config/latest/developerguide/notifications-for-AWS-Config.html
