### ISSUE TITLE
Managed log source for GitHub audit logs

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#53]
Add support for managing GitHub audit logs.

## Considerations

Enterprise audit logs are different from normal organization audit logs. Will need to research specifics.

Repo and org-level webhooks may also have different data and structures than the two types of audit logs.

May be able to generate schemas from GraphQL, OpenAPI for REST, or some other way of keeping up with all the _many_ types of GitHub events.

## Tasks

- [x] Research and discovery
    - [x] Organization audit logs
    - [x] Enterprise audit logs
    - [ ] General webhooks (repo or org-level)
    - [ ] Schema generation
- [x] ECS schemas
- [x] VRL transforms
- [x] Docs and examples

**Comment by timoguin** [comment]
Closed via #63
