### ISSUE TITLE
Managed log source for AWS ECR image scanning

### ISSUE THREAD

**Issue by timoguin** [matanolabs/matano#55]
Add support for managing data from ECR's image scanning service.

## Considerations

ECR supports automatic vulnerability scanning on push for container images.

There are two ways to get these events:

- Poll the ECR API
- Send results to Amazon Inspector, which can surface events to EventBridge

## Tasks

- [x] Research, planning, and design
- [x] ECS schemas for repository events
- [x] VRL transforms
- [ ] Docs and examples

**Comment by Samrose-Ahmed** [comment]
- Shipped through Amazon Inspector in https://github.com/matanolabs/matano/commit/105cbcc9e83e91a6cbcc1cbab33684ce3bd7d450
- Docs at https://www.matano.dev/docs/log-sources/managed-log-sources/aws/amazon-inspector
